'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Globe, Calendar, Mail, AlertTriangle } from 'lucide-react';

const TermsOfServicePage = () => {
  const lastUpdated = '09-09-2025';
  const effectiveDate = '09-09-2025';

  const servicesProvided = [
    'Automated ad campaign creation and management (currently integrated with Meta Ads)',
    'Organic growth and content management tools',
    'Audience sentiment analysis',
    'Integration with third-party analytics platforms (e.g., Google Analytics, Google Search Console, Facebook APIs)',
    'Competitive intelligence reporting',
    'Business white paper generation'
  ];

  const userResponsibilities = [
    'Provide accurate and complete account information',
    'Maintain the confidentiality of your login credentials',
    'Comply with all applicable laws and regulations when using our Service',
    'Ensure you have the rights to upload, share, or connect any content, accounts, or data with the Service'
  ];

  const prohibitedActivities = [
    'Use the Service for unlawful, harmful, or fraudulent purposes',
    'Interfere with the Service\'s functionality or security',
    'Reverse engineer, copy, or resell the Service without authorization'
  ];

  const intellectualProperty = [
    'All content, software, and technology provided through the Service are owned by amTop and protected under applicable intellectual property laws',
    'You retain rights to the content you upload, but grant us a limited, non-exclusive license to process it solely for providing the Service',
    'Reports, insights, and white papers generated by the Service may be used for your business purposes but may not be resold or redistributed without our consent'
  ];

  const paymentTerms = [
    'Certain features require a paid subscription',
    'Fees are disclosed at the time of purchase and are non-refundable unless otherwise stated',
    'We may suspend or terminate your account for non-payment'
  ];

  const liabilityLimitations = [
    'amTop shall not be liable for indirect, incidental, special, or consequential damages arising out of your use of the Service',
    'Our total liability for any claim related to the Service shall not exceed the amount you paid for the Service in the twelve (12) months preceding the claim'
  ];

  return (
    <div className="min-h-screen bg-white">
      <Header />
      
      {/* Hero Section */}
      <section className="pt-32 pb-20 bg-gradient-to-br from-gray-50 to-blue-50">
        <div className="container-max">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
              Terms and Conditions
            </h1>
            <p className="text-xl text-gray-600 mb-8 leading-relaxed">
              Welcome to amTop and our product, Agentic Marketing Solution (&quot;Service&quot;). These Terms and Conditions (&quot;Terms&quot;) govern your use of our platform and related services. By accessing or using our Service, you agree to be bound by these Terms. If you do not agree, you must not use our Service.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center text-sm text-gray-600">
              <div className="flex items-center gap-2">
                <Calendar size={16} />
                <span>Last Updated: {lastUpdated}</span>
              </div>
              <div className="flex items-center gap-2">
                <Calendar size={16} />
                <span>Effective Date: {effectiveDate}</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Eligibility */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              1. Eligibility
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              You must be at least 18 years old and have the authority to enter into this agreement on behalf of yourself or your organization. By using the Service, you represent and warrant that you meet these requirements.
            </p>
          </div>
        </div>
      </section>

      {/* Services Provided */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              2. Services Provided
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Agentic Marketing Solution includes, but is not limited to:
            </p>
          </div>

          <div className="bg-white p-8 rounded-2xl shadow-sm">
            <ul className="space-y-4">
              {servicesProvided.map((service, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-blue-500 mt-1">•</span>
                  <span className="text-gray-700 text-lg">{service}</span>
                </li>
              ))}
            </ul>
            <p className="mt-6 text-gray-600 text-lg">
              We may add, modify, or remove features at our sole discretion.
            </p>
          </div>
        </div>
      </section>

      {/* User Responsibilities */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              3. User Responsibilities
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              You agree to:
            </p>
          </div>

          <div className="bg-gray-50 p-8 rounded-2xl shadow-sm max-w-4xl mx-auto">
            <ul className="space-y-4">
              {userResponsibilities.map((responsibility, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-green-500 mt-1">✓</span>
                  <span className="text-gray-700 text-lg">{responsibility}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="mt-12">
            <h3 className="text-2xl font-bold text-gray-900 mb-6 text-center">You must not:</h3>
            <div className="bg-white p-8 rounded-2xl shadow-sm max-w-4xl mx-auto">
              <ul className="space-y-4">
                {prohibitedActivities.map((activity, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <AlertTriangle size={20} className="text-red-500 mt-1 flex-shrink-0" />
                    <span className="text-gray-700 text-lg">{activity}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Third-Party Integrations */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              4. Third-Party Integrations
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our Service connects with third-party platforms (Meta, Google, Facebook, etc.). By using these integrations, you authorize us to access and process data from these accounts. We are not responsible for availability, performance, or accuracy of third-party services. Your use of those services is subject to their own terms and policies.
            </p>
          </div>
        </div>
      </section>

      {/* Intellectual Property */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              5. Intellectual Property
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Important information about intellectual property rights.
            </p>
          </div>

          <div className="bg-gray-50 p-8 rounded-2xl shadow-sm max-w-4xl mx-auto">
            <ul className="space-y-4">
              {intellectualProperty.map((item, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-blue-500 mt-1">•</span>
                  <span className="text-gray-700 text-lg">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Fees and Payment */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              6. Fees and Payment
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Important information about billing, payments, and pricing.
            </p>
          </div>

          <div className="bg-white p-8 rounded-2xl shadow-sm max-w-4xl mx-auto">
            <ul className="space-y-4">
              {paymentTerms.map((term, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-blue-500 mt-1">•</span>
                  <span className="text-gray-700 text-lg">{term}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Disclaimer of Warranties */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              7. Disclaimer of Warranties
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind, express or implied. We do not guarantee that the Service will be error-free, uninterrupted, or produce specific results.
            </p>
          </div>
        </div>
      </section>

      {/* Limitation of Liability */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              8. Limitation of Liability
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              To the maximum extent permitted by law:
            </p>
          </div>

          <div className="bg-white p-8 rounded-2xl shadow-sm max-w-4xl mx-auto">
            <ul className="space-y-4">
              {liabilityLimitations.map((limitation, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-blue-500 mt-1">•</span>
                  <span className="text-gray-700 text-lg">{limitation}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Indemnification */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              9. Indemnification
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              You agree to indemnify and hold harmless amTop, its officers, employees, and partners from any claims, liabilities, damages, or expenses (including legal fees) arising from your use of the Service, your violation of these Terms, or your infringement of third-party rights.
            </p>
          </div>
        </div>
      </section>

      {/* Termination */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              10. Termination
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              We may suspend or terminate your account if you violate these Terms, misuse the Service, or fail to pay applicable fees. You may terminate your account at any time by contacting us. Upon termination, your access to the Service will end, but certain obligations (e.g., payment, indemnification) will survive.
            </p>
          </div>
        </div>
      </section>

      {/* Governing Law and Dispute Resolution */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              11. Governing Law and Dispute Resolution
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              These Terms are governed by the laws of [Insert Country/State]. Any disputes will be resolved in the courts of [Insert Jurisdiction], unless otherwise required by law.
            </p>
          </div>
        </div>
      </section>

      {/* Changes to the Terms */}
      <section className="py-20 bg-gray-50">
        <div className="container-max">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              12. Changes to the Terms
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              We may update these Terms from time to time. Continued use of the Service after updates constitutes acceptance of the revised Terms.
            </p>
          </div>
        </div>
      </section>

      {/* Contact Information */}
      <section className="py-20 bg-white">
        <div className="container-max">
          <div className="text-center">
            <h2 className="text-4xl font-bold text-gray-900 mb-6">
              13. Contact Us
            </h2>
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
              If you have questions about these Terms, please contact:
            </p>
            
            <div className="bg-gray-50 p-8 rounded-2xl shadow-sm max-w-2xl mx-auto">
              <div className="text-center">
                <h3 className="text-2xl font-bold text-gray-900 mb-4">amTop</h3>
                <div className="space-y-3">
                  <div className="flex items-center justify-center gap-3">
                    <Mail size={20} className="text-blue-600" />
                    <span className="text-gray-700">Email: <a href="mailto:admin@amtop.in" className="text-blue-600 font-semibold hover:underline">admin@amtop.in</a></span>
                  </div>
                  <div className="flex items-center justify-center gap-3">
                    <Globe size={20} className="text-blue-600" />
                    <span className="text-gray-700">Website: <a href="https://amtop.in" className="text-blue-600 font-semibold hover:underline">amtop.in</a></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsOfServicePage;
